runtime: java
vm: true

automatic_scaling:
  max_idle_instances: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 50
  instance_class: F2

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: /WEB-INF/account.json
