runtime: java
vm: true

resources:
  cpu: 1
  memory_gb: 1.3
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 5
  max_num_instances: 20
  cpu_utilization:
    target_utilization: 1

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: /WEB-INF/account.json
